GET http://localhost:3000/posts/5
Cookie: session=eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2NTY4ZGEzYWU2YmEwM2Y0NGIyN2Y0YTAiLCJuYW1lIjoiTGVvbmVsIiwidXNlcm5hbWUiOiJsZW9uZWxkZXYiLCJwYXNzd29yZEhhc2hlZCI6IiQyYiQxMCRjMjN1eENHa2VVOThVOGZaZHAwMkhPUmVmdFhnbVBGVlpjUU1KRW9GYkxIZlM5RUVOL2NhbSIsImVtYWlsIjoibGVvbmVsQGRldi5jb20iLCJhdmF0YXIiOnsic2VjdXJlVXJsIjoiaHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vZHptdXJpYWJ5L2ltYWdlL3VwbG9hZC92MTcwMTM2OTI1Mi9hdmF0YXJlcy91Y3FweHZ5dWppMnowZ3F3YndnOS5wbmcifSwiZm9sbG93ZXJzIjpbXSwiZm9sbG93aW5nIjpbXSwiY3JlYXRlZEF0IjoiMjAyMy0xMS0zMFQxODo1Mzo0Ni43MzFaIiwidXBkYXRlZEF0IjoiMjAyMy0xMS0zMFQxODo1Mzo0Ni43MzFaIn0.xqbXjS_ooOPtxuXZe4bzNWZl7vrROxP48GNvUdYl8As